name: Multiverse-InventoriesImporter
version: ${version}
main: org.mvplugins.multiverse.inventoriesimporter.multiverseInventoriesImporter.MultiverseInventoriesImporter
api-version: '1.18'
depend: ['Multiverse-Core', 'Multiverse-Inventories']
authors: [benwoo1110]
